require:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Naming/MethodParameterName:
  AllowedNames:
    - r
    - g
    - b

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
