version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

executors:
  default:
    docker:
      - image: cimg/ruby:3.3.6

jobs:
  doc:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec yard doc
  rspec:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check
  release:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake release

workflows:
  build:
    jobs:
      - doc
      - rubocop
      - rspec
      - release:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
